### ISSUE TITLE
[BR] 

### ISSUE THREAD

**Issue by vishw8878** [regulaforensics/flutter_face_api#13]
**lambda expressions are not supported in -source 7**

flutter_face_api-4.1.1\android\src\main\java\io\flutter\plugins\regula\faceapi\flutter_face_api\FlutterFaceApiPlugin.java:168: error: lambda expressions are not supported in -source 7
        Instance().startLiveness(getContext(), (response) -> callback.success(JSONConstructor.generateLivenessResponse(response).toString()));

**Comment by PavelMasuk** [comment]
Looks like you are using java 7, we require at least java 8 to work with our library.

**Comment by vishw8878** [comment]
@PavelMasuk  Now I am using JAVA 9.2 and its works fine
