### ISSUE TITLE
Package doesn't work in release build.

### ISSUE THREAD

**Issue by AslamThachapalli** [regulaforensics/flutter_face_api#14]
**Before Submitting, be sure to**
- [done] Update to the latest stable version.
- [done] Read and follow the guides described in the [documentation](https://docs.regulaforensics.com?utm_source=github).
- [done] Try to reproduce in our demo project.
- [done] Search for your issue in the existing GitHub issues.

**Bug Description**
The Package is not working in release mode. 
Followed the documentation and reproduced the example too. Everything was fine and worked like a charm in debug mode, but when build in release mode, the app is getting build but the face matching is not working. 
I was using the package for matching faces.

Isn't this production ready?

**Steps To Reproduce**
Just use the demo project and try to build in release mode.

**Expected behavior**
Match faces in release mode.

**Environment:**
 - Device: Realme X[Using a real device]
 - OS: Android
 - OS version: 10

**Comment by Sid1249** [comment]
why did you closed it? did you found any solution to it yet?

**Comment by AslamThachapalli** [comment]
It was a silly mistake from my end. I didn't add the internet permission in the manifest file for release mode. 
My bad. The package is working fine in release mode.
