### ISSUE TITLE
Regula.FaceSDK.init() failed

### ISSUE THREAD

**Issue by metinbinbir** [regulaforensics/flutter_face_api#18]
when i call the Regula.FaceSDK.init() function, I get the output below on iPhone 14 device.

2023-03-12 13:48:06.459611+0300 Runner[3089:1243552] flutter: Init failed:
2023-03-12 13:48:06.459659+0300 Runner[3089:1243552] flutter: {
  "success" : false,
  "error" : {
    "message" : "Core framework missed, check bundle contains binary.",
    "errorCode" : "1"
  }
}

What should I do ?

**Comment by bdtask9900** [comment]
update. gradle-7.5-all.zip and flutter_face_core

**Comment by DzmitrySmaliakou** [comment]
Hello, please check our example, starting from version 5.1 you should add Core package to your final project:
https://github.com/regulaforensics/flutter_face_api/blob/master/example/pubspec.yaml#L16
