### ISSUE TITLE
senility error ?

### ISSUE THREAD

**Issue by OmranAbhar** [regulaforensics/flutter_face_api#3]
@DmitrySmolyakov   @vyakimchik
![qw](https://user-images.githubusercontent.com/61108944/170931450-fb79fa1a-af82-4dd0-a2ba-e8dff4ef51d3.jpg)

W/regula.face.ap(12364): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, reflection, allowed)
W/regula.face.ap(12364): Accessing hidden method Landroid/app/ActivityThread;->getApplication()Landroid/app/Application; (greylist, reflection, allowed)
D/NetworkSecurityConfig(12364): No Network Security Config specified, using platform default
W/System  (12364): A resource failed to call end.
I/regula.face.ap(12364): Background concurrent copying GC freed 289(35KB) AllocSpace objects, 5(2436KB) LOS objects, 42% free, 8275KB/14MB, paused 6.985ms total 116.508ms

**Comment by vyakimchik** [comment]
Hi @OmranAbhar,

Thanks for reaching out to us!

Could you please describe in detail what issue you are experiencing? Am I right that you are experiencing the issue in our demo project?

**Comment by OmranAbhar** [comment]
thanks sir
 i don't have experience

**Comment by vyakimchik** [comment]
@OmranAbhar,

Could you please describe in detail what issue you encountered?

**Comment by OmranAbhar** [comment]
i don't know; where is problem, i think  this demo could not work for match two photos

**Comment by vyakimchik** [comment]
It seems that there is no issue on your screenshot. Please try to match other photos.

The `Similarity` text field in our demo app is used to [display](https://github.com/regulaforensics/flutter_face_api/blob/master/example/lib/main.dart#L106) the comparison result, in %, if two faces are matched.

**Comment by OmranAbhar** [comment]
![image](https://user-images.githubusercontent.com/61108944/170939373-04cb5ef4-e673-4181-80f1-6da1ecca7e95.jpeg)

**Comment by vyakimchik** [comment]
Could you please set the breakpoint to line [105](https://github.com/regulaforensics/flutter_face_api/blob/master/example/lib/main.dart#L105), perform the same steps that you did, and then copy the `str` value, and send it to us?

<img width="599" alt="Screenshot 2022-05-30 at 10 49 10" src="https://user-images.githubusercontent.com/31860804/170943635-45dfb13a-dc92-4edc-9e05-327a883da307.png">

Also, open the browser on that mobile device, go to the following [URL](https://faceapi.regulaforensics.com/api/ping), and make sure that it opens.

**Comment by OmranAbhar** [comment]
str value=> {\"matchedFaces\":[],\"unmatchedFaces\":[]}

**Comment by vyakimchik** [comment]
Thanks!

It seems that face matching did not perform as there is something with connecting to our Face API service from your device. Have you tried to open that URL on your device in the browser?
